import type { Test } from '@lvce-editor/test-with-playwright'

export const test: Test = async ({ Command, expect, KeyBoard, Locator }) => {
  await Command.execute('Layout.showPanel', 'Ports')
  await Command.execute('Ports.setPorts', [{ port: 3000 }, { port: 5173 }])
  const ports = Locator('.Ports')
  await ports.focus()
  await expect(ports).toBeFocused()
  const focused = Locator('.PortsTableRow.Focused .PortsPortColumn')
  await KeyBoard.press('ArrowDown')
  await expect(focused).toHaveText('3000')
  await KeyBoard.press('ArrowDown')
  await expect(focused).toHaveText('5173')
  await KeyBoard.press('ArrowUp')
  await expect(focused).toHaveText('3000')
  await KeyBoard.press('End')
  await expect(focused).toHaveText('5173')
  await KeyBoard.press('Home')
  await expect(focused).toHaveText('3000')
  await KeyBoard.press('Space')
  await expect(Locator('[aria-label="Port 3000 is inactive"]')).toBeVisible()
  await KeyBoard.press('Delete')
  await expect(Locator('.PortsTableBody .PortsPortColumn')).toHaveText('5173')
  await KeyBoard.press('Backspace')
  await expect(Locator('.PortsTableRow')).toHaveCount(0)
  await KeyBoard.press('a')
  const input = Locator('.AddPortInput')
  await expect(input).toBeVisible()
  await input.focus()
  await input.fill('3000')
  await KeyBoard.press('Backspace')
  await expect(input).toHaveValue('300')
  await KeyBoard.press('Escape')
  await expect(input).toBeHidden()
  await ports.focus()
  await KeyBoard.press('Shift+A')
  await expect(input).toBeVisible()
}
